%% Adaptive Control Mini-Project 4

clear;
clc;
close all;

code_dir = fileparts(mfilename('fullpath'));
if isempty(code_dir)
    code_dir = pwd;
end
project_root = fileparts(code_dir);
addpath(code_dir);

robust_modification_dir = fullfile(code_dir,'Robust_Modifications');
if exist(robust_modification_dir,'dir')
    addpath(robust_modification_dir);
end

%% Physical plant
params = struct();

params.m     = 0.486;
params.g_acc = 9.81;

params.Ixx = 0.0043;
params.Iyy = 0.0142;
params.Izz = 0.0176;
params.Ixz = 0;                  % Product of inertia neglected
params.I = diag([params.Ixx,params.Iyy,params.Izz]);

params.dcg = 0.175;
params.hcg = 0.085;
params.b   = 3.13e-5;
params.d   = 1.2e-6;
params.d_over_b = params.d/params.b;

params.B_alloc = [0, 0,          params.dcg,      params.d_over_b;
                  0, params.hcg, 0,               0;
                  0, 0,          params.d_over_b, -params.dcg];

% The first allocation column is zero, so only u2, u3, and u4 are used.
params.active_channels = 2:4;
params.B_active = params.B_alloc(:,params.active_channels);
params.G = params.I\params.B_active;

%% Nonlinear plant model
% xdot = A*x + B*(Lambda*u + Theta_plant_T*Phi(x)) + eta(x,t)
params.A = [zeros(3),eye(3);
            zeros(3),zeros(3)];
params.B = [zeros(3);
            params.G];

% Rotational coefficients for the diagonal-inertia model.
params.a_p = (params.Iyy-params.Izz)/params.Ixx;
params.a_q = (params.Izz-params.Ixx)/params.Iyy;
params.a_r = (params.Ixx-params.Iyy)/params.Izz;
params.c_d = 0.01;

params.H_true = [params.a_p,0,          0,          -params.c_d,0,          0;
                 0,         params.a_q,0,           0,         -params.c_d,0;
                 0,         0,         params.a_r,  0,          0,         -params.c_d];

% B=[0;G], so Theta_plant_T=G\H_true in the project model.
params.Theta_plant_T = params.G\params.H_true;

% This plant value remains hidden from the adaptive controller.
params.Lambda_true = eye(3);     % Nominal Task-1 effectiveness

% Task 1 is disturbance-free.
params.disturbance.type      = 'none';
params.disturbance.start_time = 0;
params.disturbance.constant  = zeros(6,1);
params.disturbance.amplitude = zeros(6,1);
params.disturbance.frequency = zeros(6,1);

%% Reference model
params.Kp = 4*eye(3);
params.Kd = 4*eye(3);
[params.Am,params.Bm,params.Cm] = Reference_Model(params);

% Ideal gains are used only for validation and plot reference lines.
params.Kx_star_T = params.Lambda_true\ ...
    (params.G\[-params.Kp,-params.Kd]);
params.Kr_star_T = params.Lambda_true\ ...
    (params.G\params.Kp);

% The minus sign in the control law gives
% Lambda*Theta_star_T=Theta_plant_T at exact matching.
params.Theta_star_T = params.Lambda_true\params.Theta_plant_T;

params.Kx_star    = params.Kx_star_T.';
params.Kr_star    = params.Kr_star_T.';
params.Theta_star = params.Theta_star_T.';

%% Lyapunov matrix
params.Q = eye(6);
params.P = lyap(params.Am',params.Q);

%% Adaptation gains
params.Gamma_x     = 50*eye(6);
params.Gamma_r     = 50*eye(3);
params.Gamma_theta = 50*eye(6);

%% Initial conditions
params.x0  = zeros(6,1);
params.xm0 = zeros(6,1);

params.Kx_hat0    = zeros(6,3);
params.Kr_hat0    = zeros(3,3);
params.Theta_hat0 = zeros(6,3);

%% Step and multisine commands
params.command.start_time = 1;
params.command.step_value = deg2rad([5;-5;8]);

% Five tones per axis improve PE without changing the command scale.
params.command.multisine_peak = deg2rad([10;10;15]);
params.command.multisine_weights = [0.30,0.24,0.19,0.15,0.12];
params.command.multisine_amplitude = ...
    params.command.multisine_peak.* ...
    params.command.multisine_weights;
params.command.multisine_frequency = [ ...
    0.31,0.53,0.79,1.07,1.37;
    0.37,0.61,0.89,1.19,1.43;
    0.43,0.67,0.97,1.27,1.51];
params.command.multisine_phase = zeros(3,5);

%% Simulation settings
params.t_final = 60;
params.ode_opts = odeset('RelTol',1e-7, ...
                         'AbsTol',1e-9, ...
                         'MaxStep',0.01);

%% Task 1 simulations
step_results = Direct_MRAC(params,'step');
multisine_results = Direct_MRAC(params,'multisine');

results = struct();
results.task1 = [step_results,multisine_results];
% Plot_Results writes image files only.
results.output_dir = fullfile(project_root,'Results');

if ~exist(results.output_dir,'dir')
    mkdir(results.output_dir);
end

results.validation = Validate_Task1(params,results.task1);

case_label = string({results.task1.label}).';
rms_tracking_error = [results.task1.rms_tracking_error].';
maximum_control_effort = [results.task1.maximum_control_effort].';
final_tracking_error = [results.task1.final_tracking_error].';
final_Kx_estimation_error = ...
    [results.task1.final_Kx_estimation_error].';
final_Kr_estimation_error = ...
    [results.task1.final_Kr_estimation_error].';
final_Theta_estimation_error = ...
    [results.task1.final_Theta_estimation_error].';
tail_rms_tracking_error = ...
    [results.validation.cases.tail_rms_tracking_error].';
max_V_increase = [results.validation.cases.max_V_increase].';

task1_summary = table(case_label,rms_tracking_error, ...
    tail_rms_tracking_error,maximum_control_effort, ...
    final_tracking_error,final_Kx_estimation_error, ...
    final_Kr_estimation_error,final_Theta_estimation_error, ...
    max_V_increase);

fprintf('\nTask 1 validation passed.\n');
fprintf('  controllability rank: %d of %d\n', ...
    results.validation.controllability_rank,size(params.A,1));
fprintf('  maximum Re(lambda(Am)): %.3e\n', ...
    results.validation.reference_model_spectral_abscissa);
fprintf('  largest matching residual: %.3e\n\n',max([ ...
    results.validation.state_matching_residual, ...
    results.validation.command_matching_residual, ...
    results.validation.uncertainty_matching_residual]));
disp(task1_summary);

%% Task 2: indirect MRAC and fair direct-MRAC comparison
% A nonidentity positive-definite Lambda makes its identification meaningful.
% Direct and indirect controllers use the same plant and command.
task2_params = params;
task2_params.t_final = 120;
task2_params.Lambda_true = [0.80,0.05,0.00;
                            0.05,1.10,0.03;
                            0.00,0.03,0.90];

task2_params.Kx_star_T = task2_params.Lambda_true\ ...
    (task2_params.G\[-task2_params.Kp,-task2_params.Kd]);
task2_params.Kr_star_T = task2_params.Lambda_true\ ...
    (task2_params.G\task2_params.Kp);
task2_params.Theta_star_T = task2_params.Lambda_true\ ...
    task2_params.Theta_plant_T;
task2_params.Kx_star = task2_params.Kx_star_T.';
task2_params.Kr_star = task2_params.Kr_star_T.';
task2_params.Theta_star = task2_params.Theta_star_T.';

% Series-parallel state predictor.
task2_params.indirect.Lambda_hat0 = eye(3);
task2_params.indirect.Theta_plant_hat_T0 = zeros(3,6);
task2_params.indirect.x_predictor0 = task2_params.x0;
task2_params.indirect.L_id = 4*eye(6);
task2_params.indirect.Q_id = eye(6);
task2_params.indirect.P_id = lyap( ...
    (-task2_params.indirect.L_id)',task2_params.indirect.Q_id);
task2_params.indirect.Gamma_W = diag([ ...
    200*ones(1,3),400*ones(1,6)]);
task2_params.indirect.lambda_singular_value_floor = 0.20;
task2_params.indirect.pe_window = 10;

task2_direct_step = Direct_MRAC(task2_params,'step');
task2_indirect_step = Indirect_MRAC(task2_params,'step');
task2_direct_multisine = Direct_MRAC(task2_params,'multisine');
task2_indirect_multisine = Indirect_MRAC(task2_params,'multisine');

results.task2 = struct();
results.task2.direct = [task2_direct_step,task2_direct_multisine];
results.task2.indirect = [task2_indirect_step,task2_indirect_multisine];
results.task2.validation = Validate_Task2( ...
    task2_params,results.task2.direct,results.task2.indirect);

task2_cases = {task2_direct_step,task2_indirect_step, ...
    task2_direct_multisine,task2_indirect_multisine};
n_task2_cases = numel(task2_cases);
controller_name = strings(n_task2_cases,1);
command_name = strings(n_task2_cases,1);
rms_tracking_error = zeros(n_task2_cases,1);
maximum_control_effort = zeros(n_task2_cases,1);
final_tracking_error = zeros(n_task2_cases,1);
final_Lambda_estimation_error = nan(n_task2_cases,1);
final_Theta_estimation_error = zeros(n_task2_cases,1);
final_Kx_estimation_error = zeros(n_task2_cases,1);
final_Kr_estimation_error = zeros(n_task2_cases,1);
final_prediction_error = nan(n_task2_cases,1);
information_effective_rank = nan(n_task2_cases,1);
final_PE_window_min_eigenvalue = nan(n_task2_cases,1);

for ic = 1:n_task2_cases
    case_result = task2_cases{ic};
    controller_name(ic) = string(case_result.controller);
    command_name(ic) = string(case_result.label);
    rms_tracking_error(ic) = case_result.rms_tracking_error;
    maximum_control_effort(ic) = case_result.maximum_control_effort;
    final_tracking_error(ic) = case_result.final_tracking_error;
    final_Theta_estimation_error(ic) = ...
        case_result.final_Theta_estimation_error;
    final_Kx_estimation_error(ic) = ...
        case_result.final_Kx_estimation_error;
    final_Kr_estimation_error(ic) = ...
        case_result.final_Kr_estimation_error;

    if strcmp(case_result.controller,'Indirect MRAC')
        final_Lambda_estimation_error(ic) = ...
            case_result.final_Lambda_estimation_error;
        final_prediction_error(ic) = ...
            case_result.final_prediction_error;
        information_effective_rank(ic) = ...
            case_result.information_effective_rank;
        final_PE_window_min_eigenvalue(ic) = ...
            case_result.pe_min_eigenvalue(end);
    end
end

task2_summary = table(controller_name,command_name, ...
    rms_tracking_error,maximum_control_effort,final_tracking_error, ...
    final_Lambda_estimation_error,final_Theta_estimation_error, ...
    final_Kx_estimation_error,final_Kr_estimation_error, ...
    final_prediction_error,information_effective_rank, ...
    final_PE_window_min_eigenvalue);

fprintf('\nTask 2 validation passed.\n');
fprintf('  true Lambda condition number: %.3f\n', ...
    cond(task2_params.Lambda_true));
fprintf('  estimator information ranks (step/multisine): %d / %d of 9\n\n', ...
    task2_indirect_step.information_effective_rank, ...
    task2_indirect_multisine.information_effective_rank);
disp(task2_summary);

%% Task 3: integral augmentation under a matched step disturbance
task3_params = params;
task3_params.t_final = 80;
task3_params.command.step_value = zeros(3,1);
task3_params.disturbance.type = 'constant';
task3_params.disturbance.start_time = 20;
task3_params.task3.input_disturbance = [0.004;-0.003;0.004];
task3_params.disturbance.constant = task3_params.B ...
    *task3_params.task3.input_disturbance;

% Both cases start from the same estimates, isolating integral augmentation.
task3_params.Kx_hat0 = task3_params.Kx_star;
task3_params.Kr_hat0 = task3_params.Kr_star;
task3_params.Theta_hat0 = task3_params.Theta_star;

task3_params.task3.Ki_des = 2*eye(3);
task3_integral_injection = [zeros(3);-task3_params.task3.Ki_des];
task3_params.task3.Abar_m = [ ...
    task3_params.Am,task3_integral_injection;
    task3_params.Cm,zeros(3)];
task3_params.task3.Bbar = [task3_params.B;zeros(3,3)];
task3_params.task3.Qbar = eye(9);
task3_params.task3.Pbar = lyap( ...
    task3_params.task3.Abar_m',task3_params.task3.Qbar);
task3_params.task3.Gamma_bar = blkdiag( ...
    task3_params.Gamma_x,25*eye(3));
task3_params.task3.Ki_star_T = task3_params.Lambda_true\ ...
    (task3_params.G\(-task3_params.task3.Ki_des));
task3_params.task3.Ki_star = ...
    task3_params.task3.Ki_star_T.';
task3_params.task3.eI0 = zeros(3,1);
task3_params.task3.Ki_hat0 = zeros(3,3);
task3_params.task3.steady_state_window = 15;

task3_baseline = Integral_MRAC(task3_params,'step','baseline');
task3_integral = Integral_MRAC(task3_params,'step','integral');

results.task3 = struct();
results.task3.baseline = task3_baseline;
results.task3.integral = task3_integral;
results.task3.validation = Validate_Task3( ...
    task3_params,task3_baseline,task3_integral);

controller_name = string({ ...
    task3_baseline.controller;task3_integral.controller});
rms_tracking_error = [ ...
    task3_baseline.rms_tracking_error;
    task3_integral.rms_tracking_error];
post_disturbance_rms_output_error = [ ...
    task3_baseline.post_disturbance_rms_output_error;
    task3_integral.post_disturbance_rms_output_error];
steady_state_rms_output_error = [ ...
    task3_baseline.steady_state_rms_output_error;
    task3_integral.steady_state_rms_output_error];
peak_post_disturbance_output_error = [ ...
    task3_baseline.peak_post_disturbance_output_error;
    task3_integral.peak_post_disturbance_output_error];
maximum_control_effort = [ ...
    task3_baseline.maximum_control_effort;
    task3_integral.maximum_control_effort];
final_output_error = [ ...
    task3_baseline.final_output_error;
    task3_integral.final_output_error];
final_integral_state = [ ...
    task3_baseline.final_integral_state;
    task3_integral.final_integral_state];

task3_summary = table(controller_name,rms_tracking_error, ...
    post_disturbance_rms_output_error,steady_state_rms_output_error, ...
    peak_post_disturbance_output_error,maximum_control_effort, ...
    final_output_error,final_integral_state);

fprintf('\nTask 3 validation passed.\n');
fprintf('  maximum Re(lambda(Abar_m)): %.3e\n', ...
    results.task3.validation.augmented_spectral_abscissa);
fprintf('  steady-state output-error improvement: %.2f x\n\n', ...
    results.task3.validation.steady_state_improvement_factor);
disp(task3_summary);

%% Task 4: robust modifications under one bounded disturbance
task4_params = params;
task4_params.t_final = 120;
task4_params.ode_opts = odeset('RelTol',1e-7, ...
    'AbsTol',1e-9,'MaxStep',0.02);

% Starting at the matching gains isolates disturbance-driven parameter drift.
% Only the projection method receives the prior bounds defined below.
task4_params.Kx_hat0 = task4_params.Kx_star;
task4_params.Kr_hat0 = task4_params.Kr_star;
task4_params.Theta_hat0 = task4_params.Theta_star;

% Every method sees the same bounded, three-tone disturbance.
task4_params.disturbance.type = 'multisine';
task4_params.disturbance.start_time = 0;
task4_params.disturbance.amplitude = [ ...
    3.0e-4,2.0e-4,1.0e-4;
    2.5e-4,2.0e-4,1.5e-4;
    2.8e-4,1.8e-4,1.2e-4;
    3.0e-3,2.0e-3,1.0e-3;
    2.8e-3,1.8e-3,1.2e-3;
    3.2e-3,2.1e-3,1.1e-3];
task4_params.disturbance.frequency = [ ...
    0.17,0.43,0.79;
    0.23,0.53,0.91;
    0.29,0.61,1.03;
    0.19,0.47,0.83;
    0.31,0.67,1.09;
    0.37,0.73,1.19];
task4_params.disturbance.phase = [ ...
    0.0,0.4,0.8;
    0.2,0.6,1.0;
    0.4,0.8,1.2;
    0.6,1.0,1.4;
    0.8,1.2,1.6;
    1.0,1.4,1.8];

% Triangle-inequality bound on ||eta(t)||_2.
task4_params.task4.disturbance_bound = norm( ...
    sum(abs(task4_params.disturbance.amplitude),2),2);
task4_params.task4.deadzone_minimum = ...
    2*norm(task4_params.P,2) ...
    *task4_params.task4.disturbance_bound ...
    /min(eig(task4_params.Q));
task4_params.task4.deadzone_epsilon = ...
    1.10*task4_params.task4.deadzone_minimum;
task4_params.task4.sigma = 2.0e-5;
task4_params.task4.sigma_e = 5.0e-3;
task4_params.task4.tail_window = 20;

% The projection box surrounds the full matching parameter set.
task4_params.task4.projection.Kx_limit = ...
    abs(task4_params.Kx_star)+0.002;
task4_params.task4.projection.Kr_limit = ...
    abs(task4_params.Kr_star)+0.002;
task4_params.task4.projection.Theta_limit = ...
    abs(task4_params.Theta_star)+0.001;
task4_params.task4.projection.Kx_lower = ...
    -task4_params.task4.projection.Kx_limit;
task4_params.task4.projection.Kx_upper = ...
    task4_params.task4.projection.Kx_limit;
task4_params.task4.projection.Kr_lower = ...
    -task4_params.task4.projection.Kr_limit;
task4_params.task4.projection.Kr_upper = ...
    task4_params.task4.projection.Kr_limit;
task4_params.task4.projection.Theta_lower = ...
    -task4_params.task4.projection.Theta_limit;
task4_params.task4.projection.Theta_upper = ...
    task4_params.task4.projection.Theta_limit;

task4_method_names = { ...
    'baseline','deadzone','sigma','emod','projection'};
task4_cases = cell(size(task4_method_names));
for method_index = 1:numel(task4_method_names)
    task4_cases{method_index} = Direct_MRAC( ...
        task4_params,'multisine', ...
        task4_method_names{method_index});
end

results.task4 = struct();
results.task4.cases = task4_cases;
results.task4.disturbance_bound = ...
    task4_params.task4.disturbance_bound;
results.task4.deadzone_epsilon = ...
    task4_params.task4.deadzone_epsilon;
results.task4.sigma = task4_params.task4.sigma;
results.task4.sigma_e = task4_params.task4.sigma_e;
results.task4.validation = Validate_Task4( ...
    task4_params,task4_cases);

n_task4_cases = numel(task4_cases);
controller_name = strings(n_task4_cases,1);
rms_tracking_error = zeros(n_task4_cases,1);
tail_rms_tracking_error = zeros(n_task4_cases,1);
peak_tracking_error = zeros(n_task4_cases,1);
maximum_control_effort = zeros(n_task4_cases,1);
final_parameter_error = zeros(n_task4_cases,1);
maximum_parameter_error = zeros(n_task4_cases,1);
parameter_excursion_from_initial = zeros(n_task4_cases,1);
adaptation_duty_fraction = ones(n_task4_cases,1);
projection_active_fraction = zeros(n_task4_cases,1);

for method_index = 1:n_task4_cases
    case_result = task4_cases{method_index};
    controller_name(method_index) = string(case_result.controller);
    rms_tracking_error(method_index) = ...
        case_result.rms_tracking_error;
    tail_rms_tracking_error(method_index) = ...
        case_result.tail_rms_tracking_error;
    peak_tracking_error(method_index) = ...
        case_result.peak_tracking_error;
    maximum_control_effort(method_index) = ...
        case_result.maximum_control_effort;
    final_parameter_error(method_index) = ...
        case_result.final_parameter_error;
    maximum_parameter_error(method_index) = ...
        case_result.maximum_parameter_error;
    parameter_excursion_from_initial(method_index) = ...
        case_result.parameter_excursion_from_initial;
    adaptation_duty_fraction(method_index) = ...
        case_result.adaptation_duty_fraction;
    projection_active_fraction(method_index) = ...
        case_result.projection_active_fraction;
end

task4_summary = table(controller_name,rms_tracking_error, ...
    tail_rms_tracking_error,peak_tracking_error, ...
    maximum_control_effort,final_parameter_error, ...
    maximum_parameter_error,parameter_excursion_from_initial, ...
    adaptation_duty_fraction,projection_active_fraction);

fprintf('\nTask 4 validation passed.\n');
fprintf('  rigorous disturbance bound: %.4e\n', ...
    results.task4.validation.disturbance_bound);
fprintf('  dead-zone threshold/minimum: %.4e / %.4e\n', ...
    task4_params.task4.deadzone_epsilon, ...
    task4_params.task4.deadzone_minimum);
fprintf('  maximum projection-set violation: %.3e\n\n', ...
    results.task4.validation.projection_max_violation);
disp(task4_summary);

%% Task 5: output feedback, observer-based LTR, and augmentation
task5_params = params;
task5_params.t_final = 80;
task5_params.ode_opts = odeset('RelTol',1e-7, ...
    'AbsTol',1e-9,'MaxStep',0.005);
task5_params.disturbance.type = 'none';

% Matching initial gains isolate observer recovery and added uncertainty.
task5_params.Kx_hat0 = task5_params.Kx_star;
task5_params.Kr_hat0 = task5_params.Kr_star;
task5_params.Theta_hat0 = task5_params.Theta_star;

task5_params.task5.rho_values = [1e2,1,1e-2,1e-4];
task5_params.task5.frequency = logspace(-2,2.5,260);
task5_design = Observer_LTR(task5_params, ...
    task5_params.task5.rho_values, ...
    task5_params.task5.frequency);
task5_params.task5.design = task5_design;
task5_params.task5.baseline_rho_index = 1;
task5_params.task5.selected_rho_index = 3;
task5_params.task5.L_baseline = task5_design.L(:,:, ...
    task5_params.task5.baseline_rho_index);
task5_params.task5.L_selected = task5_design.L(:,:, ...
    task5_params.task5.selected_rho_index);

task5_params.task5.xhat0 = task5_params.x0;
task5_params.task5.measurement_noise_amplitude = ...
    deg2rad([0.002;0.002;0.003]);
task5_params.task5.measurement_noise_frequency = ...
    [7.3;8.1;9.2];
task5_params.task5.measurement_noise_phase = ...
    [0.0;0.7;1.3];
task5_params.task5.tail_window = 15;

% The augmentation handles a bounded matched term missing from Phi(x).
task5_params.task5.W_true_T = [ ...
     0.0030,-0.0010, 0.0015, 0.0020;
    -0.0010, 0.0025,-0.0010, 0.0015;
     0.0010,-0.0015, 0.0030,-0.0020];
task5_params.task5.W_star_T = ...
    task5_params.Lambda_true\task5_params.task5.W_true_T;
task5_params.task5.W_star = task5_params.task5.W_star_T.';
task5_params.task5.W_hat0 = zeros(4,3);
task5_params.task5.Gamma_augmentation = 5*eye(4);
task5_params.task5.augmentation_sigma = 5e-3;

task5_configuration_names = { ...
    'fullstate','output_baseline','ltr','augmented'};
task5_cases = cell(size(task5_configuration_names));
for configuration_index = 1:numel(task5_configuration_names)
    task5_cases{configuration_index} = OutputFeedback_MRAC( ...
        task5_params,'multisine', ...
        task5_configuration_names{configuration_index});
end

results.task5 = struct();
results.task5.cases = task5_cases;
results.task5.design = task5_design;
results.task5.validation = Validate_Task5( ...
    task5_params,task5_cases,task5_design);

n_task5_cases = numel(task5_cases);
controller_name = strings(n_task5_cases,1);
rms_tracking_error = zeros(n_task5_cases,1);
tail_rms_tracking_error = zeros(n_task5_cases,1);
rms_observer_error = zeros(n_task5_cases,1);
tail_rms_observer_error = zeros(n_task5_cases,1);
rms_innovation = zeros(n_task5_cases,1);
maximum_control_effort = zeros(n_task5_cases,1);
maximum_augmentation_effort = zeros(n_task5_cases,1);
final_parameter_error = zeros(n_task5_cases,1);
final_augmentation_error = nan(n_task5_cases,1);

for configuration_index = 1:n_task5_cases
    case_result = task5_cases{configuration_index};
    controller_name(configuration_index) = ...
        string(case_result.controller);
    rms_tracking_error(configuration_index) = ...
        case_result.rms_tracking_error;
    tail_rms_tracking_error(configuration_index) = ...
        case_result.tail_rms_tracking_error;
    rms_observer_error(configuration_index) = ...
        case_result.rms_observer_error;
    tail_rms_observer_error(configuration_index) = ...
        case_result.tail_rms_observer_error;
    rms_innovation(configuration_index) = ...
        case_result.rms_innovation;
    maximum_control_effort(configuration_index) = ...
        case_result.maximum_control_effort;
    maximum_augmentation_effort(configuration_index) = ...
        case_result.maximum_augmentation_effort;
    final_parameter_error(configuration_index) = ...
        case_result.final_parameter_error;
    final_augmentation_error(configuration_index) = ...
        case_result.final_augmentation_error;
end

task5_summary = table(controller_name,rms_tracking_error, ...
    tail_rms_tracking_error,rms_observer_error, ...
    tail_rms_observer_error,rms_innovation, ...
    maximum_control_effort,maximum_augmentation_effort, ...
    final_parameter_error,final_augmentation_error);

fprintf('\nTask 5 validation passed.\n');
fprintf('  observability rank: %d of %d\n', ...
    results.task5.validation.observability_rank,size(params.A,1));
fprintf('  baseline/selected rho: %.1e / %.1e\n', ...
    task5_design.rho(task5_params.task5.baseline_rho_index), ...
    task5_design.rho(task5_params.task5.selected_rho_index));
fprintf('  LTR log-singular-value RMSE improvement: %.2f x\n', ...
    results.task5.validation.ltr_recovery_improvement);
fprintf('  augmentation tail-error improvement over LTR: %.2f x\n\n', ...
    results.task5.validation.augmentation_improvement);
disp(task5_summary);

%% Task 6: common five-scenario comparison
task6_params = params;
task6_params.t_final = 35;
task6_params.ode_opts = odeset('RelTol',1e-6, ...
    'AbsTol',1e-8,'MaxStep',0.04);
task6_params.Kx_hat0 = task6_params.Kx_star;
task6_params.Kr_hat0 = task6_params.Kr_star;
task6_params.Theta_hat0 = task6_params.Theta_star;

task6_params.indirect = task2_params.indirect;
task6_params.indirect.Lambda_hat0 = task6_params.Lambda_true;
task6_params.indirect.Theta_plant_hat_T0 = ...
    task6_params.Theta_plant_T;
task6_params.indirect.x_predictor0 = task6_params.x0;
task6_params.indirect.pe_window = 6;

task6_params.task3 = task3_params.task3;
task6_params.task3.Ki_star_T = task6_params.Lambda_true\ ...
    (task6_params.G\(-task6_params.task3.Ki_des));
task6_params.task3.Ki_star = task6_params.task3.Ki_star_T.';
task6_params.task3.Ki_hat0 = task6_params.task3.Ki_star;
task6_params.task3.steady_state_window = 8;

task6_params.task4 = task4_params.task4;
task6_params.task4.tail_window = 8;

task6_params.task5 = task5_params.task5;
task6_params.task5.measurement_noise_amplitude = zeros(3,1);
task6_params.task5.W_true_T = zeros(3,4);
task6_params.task5.W_star_T = zeros(3,4);
task6_params.task5.W_star = zeros(4,3);
task6_params.task5.W_hat0 = zeros(4,3);
task6_params.task5.tail_window = 8;

results.task6 = run_task6_evaluation(task6_params);
fprintf('\nTask 6 comprehensive evaluation passed.\n');
fprintf('  scenarios/controllers: %d / %d\n\n', ...
    numel(results.task6.scenario_labels), ...
    numel(results.task6.controller_labels));
disp(results.task6.summary);

%% Export all figures
Plot_Results(results);

function validation = Validate_Task1(params,task1)
%VALIDATE_TASK1 Internal consistency checks for the Task-1 simulation.

    if numel(task1) ~= 2
        error('Validate_Task1:CaseCount', ...
            'Expected the step and multisine Task-1 simulations.');
    end

    validation = struct();
    validation.reference_model_spectral_abscissa = ...
        max(real(eig(params.Am)));
    validation.controllability_rank = rank(ctrb(params.A,params.B));
    validation.input_effectiveness_min_eigenvalue = ...
        min(eig((params.Lambda_true+params.Lambda_true.')/2));
    validation.lyapunov_P_min_eigenvalue = ...
        min(eig((params.P+params.P.')/2));
    validation.state_matching_residual = norm( ...
        params.A+params.B*params.Lambda_true*params.Kx_star_T ...
        -params.Am,'fro');
    validation.command_matching_residual = norm( ...
        params.B*params.Lambda_true*params.Kr_star_T ...
        -params.Bm,'fro');
    validation.uncertainty_matching_residual = norm( ...
        params.Lambda_true*params.Theta_star_T ...
        -params.Theta_plant_T,'fro');
    validation.lyapunov_equation_residual = norm( ...
        params.Am.'*params.P+params.P*params.Am+params.Q,'fro');

    assert(validation.reference_model_spectral_abscissa < 0, ...
        'Validate_Task1:UnstableReferenceModel','Am must be Hurwitz.');
    assert(validation.controllability_rank == size(params.A,1), ...
        'Validate_Task1:UncontrollablePlant', ...
        'The pair (A,B) must be controllable.');
    assert(norm(params.Lambda_true-params.Lambda_true.','fro') < 1e-12 ...
        && validation.input_effectiveness_min_eigenvalue > 0, ...
        'Validate_Task1:InvalidInputEffectiveness', ...
        ['The implemented Lyapunov proof requires Lambda_true to be ' ...
         'symmetric positive definite.']);
    assert(validation.lyapunov_P_min_eigenvalue > 0, ...
        'Validate_Task1:InvalidLyapunovMatrix', ...
        'The Lyapunov solution P must be positive definite.');

    algebra_tolerance = 1e-9;
    assert(validation.state_matching_residual < algebra_tolerance, ...
        'Validate_Task1:StateMatchingFailure', ...
        'The state-feedback matching equation is not satisfied.');
    assert(validation.command_matching_residual < algebra_tolerance, ...
        'Validate_Task1:CommandMatchingFailure', ...
        'The command matching equation is not satisfied.');
    assert(validation.uncertainty_matching_residual < algebra_tolerance, ...
        'Validate_Task1:UncertaintyMatchingFailure', ...
        'The uncertainty cancellation matching equation is not satisfied.');
    assert(validation.lyapunov_equation_residual < algebra_tolerance, ...
        'Validate_Task1:LyapunovEquationFailure', ...
        'P does not satisfy the requested Lyapunov equation.');

    validation.cases = repmat(struct( ...
        'label','', ...
        'max_V_increase',NaN, ...
        'tail_rms_tracking_error',NaN, ...
        'maximum_absolute_state',NaN, ...
        'all_values_finite',false),1,numel(task1));

    for ic = 1:numel(task1)
        case_result = task1(ic);
        error_norm_squared = sum(case_result.e.^2,2);
        tail_start = max(1,floor(0.8*numel(case_result.t)));
        tail_time = case_result.t(tail_start:end);
        tail_error = error_norm_squared(tail_start:end);

        case_validation = struct();
        case_validation.label = case_result.label;
        case_validation.max_V_increase = max(diff(case_result.V));
        case_validation.tail_rms_tracking_error = sqrt( ...
            trapz(tail_time,tail_error)/(tail_time(end)-tail_time(1)));
        case_validation.maximum_absolute_state = ...
            max(abs(case_result.x),[],'all');
        case_validation.all_values_finite = ...
            all(isfinite([case_result.x,case_result.xm, ...
                case_result.e,case_result.u]),'all');

        V_tolerance = 1e-10*max(1,abs(case_result.V(1)));
        assert(case_validation.all_values_finite, ...
            'Validate_Task1:NonFiniteTrajectory', ...
            '%s produced a nonfinite trajectory.',case_result.label);
        assert(case_validation.max_V_increase <= V_tolerance, ...
            'Validate_Task1:LyapunovIncrease', ...
            '%s violates the nonincreasing Lyapunov check.', ...
            case_result.label);
        validation.cases(ic) = case_validation;
    end
end

function validation = Validate_Task2(params,direct_results,indirect_results)
%VALIDATE_TASK2 Internal consistency checks for the Task-2 comparison.

    if numel(direct_results) ~= 2 || numel(indirect_results) ~= 2
        error('Validate_Task2:CaseCount', ...
            'Expected step and multisine results for both controllers.');
    end

    symmetric_lambda = ...
        (params.Lambda_true+params.Lambda_true.')/2;
    validation = struct();
    validation.lambda_symmetry_residual = norm( ...
        params.Lambda_true-params.Lambda_true.','fro');
    validation.lambda_min_eigenvalue = min(eig(symmetric_lambda));
    validation.lambda_condition_number = cond(params.Lambda_true);
    validation.identifier_lyapunov_residual = norm( ...
        (-params.indirect.L_id).'*params.indirect.P_id ...
        + params.indirect.P_id*(-params.indirect.L_id) ...
        + params.indirect.Q_id,'fro');
    validation.state_matching_residual = norm( ...
        params.A+params.B*params.Lambda_true*params.Kx_star_T ...
        -params.Am,'fro');
    validation.command_matching_residual = norm( ...
        params.B*params.Lambda_true*params.Kr_star_T ...
        -params.Bm,'fro');
    validation.uncertainty_matching_residual = norm( ...
        params.Lambda_true*params.Theta_star_T ...
        -params.Theta_plant_T,'fro');

    assert(validation.lambda_symmetry_residual < 1e-12 ...
        && validation.lambda_min_eigenvalue > 0, ...
        'Validate_Task2:InvalidLambda', ...
        'The comparison Lambda_true must be symmetric positive definite.');
    assert(validation.identifier_lyapunov_residual < 1e-9, ...
        'Validate_Task2:IdentifierLyapunovFailure', ...
        'P_id does not solve the identifier Lyapunov equation.');
    assert(max([validation.state_matching_residual, ...
        validation.command_matching_residual, ...
        validation.uncertainty_matching_residual]) < 1e-9, ...
        'Validate_Task2:MatchingFailure', ...
        'The Task-2 ideal matching equations are not satisfied.');

    validation.cases = repmat(struct( ...
        'label','', ...
        'direct_rms_tracking_error',NaN, ...
        'indirect_rms_tracking_error',NaN, ...
        'indirect_final_prediction_error',NaN, ...
        'information_effective_rank',NaN, ...
        'minimum_regularized_singular_value',NaN), ...
        1,numel(indirect_results));

    for ic = 1:numel(indirect_results)
        direct_case = direct_results(ic);
        indirect_case = indirect_results(ic);

        assert(strcmp(direct_case.command_type, ...
            indirect_case.command_type), ...
            'Validate_Task2:CommandMismatch', ...
            'Direct and indirect result arrays are not aligned.');
        assert(all(isfinite([direct_case.x,direct_case.xm, ...
            direct_case.e,direct_case.u]),'all'), ...
            'Validate_Task2:NonFiniteDirectTrajectory', ...
            '%s produced a nonfinite direct-MRAC trajectory.', ...
            direct_case.label);
        assert(all(isfinite([indirect_case.x,indirect_case.xm, ...
            indirect_case.x_predictor,indirect_case.e, ...
            indirect_case.u]),'all'), ...
            'Validate_Task2:NonFiniteIndirectTrajectory', ...
            '%s produced a nonfinite indirect-MRAC trajectory.', ...
            indirect_case.label);
        assert(indirect_case.t(end) >= ...
            params.t_final*(1-10*eps), ...
            'Validate_Task2:IncompleteSimulation', ...
            '%s did not reach the requested final time.', ...
            indirect_case.label);

        minimum_regularized_singular_value = min( ...
            indirect_case.minimum_used_singular_value);
        assert(minimum_regularized_singular_value >= ...
            params.indirect.lambda_singular_value_floor*(1-1e-12), ...
            'Validate_Task2:UnsafeInverse', ...
            'The certainty-equivalence inverse violated its singular-value floor.');

        case_validation = struct();
        case_validation.label = indirect_case.label;
        case_validation.direct_rms_tracking_error = ...
            direct_case.rms_tracking_error;
        case_validation.indirect_rms_tracking_error = ...
            indirect_case.rms_tracking_error;
        case_validation.indirect_final_prediction_error = ...
            indirect_case.final_prediction_error;
        case_validation.information_effective_rank = ...
            indirect_case.information_effective_rank;
        case_validation.minimum_regularized_singular_value = ...
            minimum_regularized_singular_value;
        validation.cases(ic) = case_validation;
    end
end

function validation = Validate_Task3(params,baseline,integral)
%VALIDATE_TASK3 Internal checks for the integral-augmentation comparison.

    validation = struct();
    validation.augmented_spectral_abscissa = max( ...
        real(eig(params.task3.Abar_m)));
    validation.Pbar_min_eigenvalue = min(eig( ...
        (params.task3.Pbar+params.task3.Pbar.')/2));
    validation.augmented_lyapunov_residual = norm( ...
        params.task3.Abar_m.'*params.task3.Pbar ...
        + params.task3.Pbar*params.task3.Abar_m ...
        + params.task3.Qbar,'fro');
    integral_injection = [zeros(3);-params.task3.Ki_des];
    validation.integral_matching_residual = norm( ...
        params.B*params.Lambda_true*params.task3.Ki_star_T ...
        -integral_injection,'fro');
    validation.steady_state_improvement_factor = ...
        baseline.steady_state_rms_output_error ...
        /integral.steady_state_rms_output_error;

    assert(validation.augmented_spectral_abscissa < 0, ...
        'Validate_Task3:UnstableAugmentedModel', ...
        'The augmented reference-error model must be Hurwitz.');
    assert(validation.Pbar_min_eigenvalue > 0 ...
        && validation.augmented_lyapunov_residual < 1e-9, ...
        'Validate_Task3:InvalidLyapunovSolution', ...
        'Pbar must be positive definite and solve the Lyapunov equation.');
    assert(validation.integral_matching_residual < 1e-9, ...
        'Validate_Task3:IntegralMatchingFailure', ...
        'The ideal integral gain does not match the augmented model.');
    assert(all(isfinite([baseline.x,baseline.e,baseline.u]),'all') ...
        && all(isfinite([integral.x,integral.e,integral.eI, ...
            integral.u]),'all'), ...
        'Validate_Task3:NonFiniteTrajectory', ...
        'A Task-3 controller produced a nonfinite trajectory.');
    assert(validation.steady_state_improvement_factor > 1, ...
        'Validate_Task3:NoIntegralImprovement', ...
        'Integral augmentation did not improve steady-state output error.');
end

function validation = Validate_Task4(params,task4_cases)
%VALIDATE_TASK4 Internal UUB and projection-set consistency checks.

    if numel(task4_cases) ~= 5
        error('Validate_Task4:CaseCount', ...
            'Expected baseline and four robust Task-4 simulations.');
    end

    method_names = cellfun(@(item) item.robust_method, ...
        task4_cases,'UniformOutput',false);
    required_methods = {'baseline','deadzone','sigma', ...
        'emod','projection'};
    assert(isequal(method_names,required_methods), ...
        'Validate_Task4:MethodOrder', ...
        'The required robust methods are incomplete or out of order.');

    validation = struct();
    validation.disturbance_bound = ...
        params.task4.disturbance_bound;
    validation.deadzone_minimum = ...
        params.task4.deadzone_minimum;
    validation.deadzone_threshold = ...
        params.task4.deadzone_epsilon;

    actual_disturbance_norm = zeros(numel(task4_cases),1);
    maximum_state_norm = zeros(numel(task4_cases),1);
    for case_index = 1:numel(task4_cases)
        case_result = task4_cases{case_index};
        assert(all(isfinite([case_result.x,case_result.e, ...
            case_result.u,case_result.parameter_error_norm]),'all'), ...
            'Validate_Task4:NonFiniteTrajectory', ...
            'A Task-4 method produced a nonfinite trajectory.');
        actual_disturbance_norm(case_index) = max( ...
            vecnorm(case_result.eta,2,2));
        maximum_state_norm(case_index) = max( ...
            vecnorm(case_result.x,2,2));
    end
    validation.actual_maximum_disturbance = ...
        max(actual_disturbance_norm);
    validation.maximum_state_norm = maximum_state_norm;

    projection_case = task4_cases{ ...
        strcmp(method_names,'projection')};
    projection_bounds = params.task4.projection;
    Kx_upper = reshape(projection_bounds.Kx_upper,1,6,3);
    Kx_lower = reshape(projection_bounds.Kx_lower,1,6,3);
    Kr_upper = reshape(projection_bounds.Kr_upper,1,3,3);
    Kr_lower = reshape(projection_bounds.Kr_lower,1,3,3);
    Theta_upper = reshape(projection_bounds.Theta_upper,1,6,3);
    Theta_lower = reshape(projection_bounds.Theta_lower,1,6,3);
    projection_violations = [ ...
        max(projection_case.Kx_hat-Kx_upper,[],'all'), ...
        max(Kx_lower-projection_case.Kx_hat,[],'all'), ...
        max(projection_case.Kr_hat-Kr_upper,[],'all'), ...
        max(Kr_lower-projection_case.Kr_hat,[],'all'), ...
        max(projection_case.Theta_hat-Theta_upper,[],'all'), ...
        max(Theta_lower-projection_case.Theta_hat,[],'all')];
    validation.projection_max_violation = ...
        max([0,projection_violations]);

    validation.ideal_set_margin = min([ ...
        min(params.Kx_star-projection_bounds.Kx_lower,[],'all'), ...
        min(projection_bounds.Kx_upper-params.Kx_star,[],'all'), ...
        min(params.Kr_star-projection_bounds.Kr_lower,[],'all'), ...
        min(projection_bounds.Kr_upper-params.Kr_star,[],'all'), ...
        min(params.Theta_star-projection_bounds.Theta_lower,[],'all'), ...
        min(projection_bounds.Theta_upper-params.Theta_star,[],'all')]);
    validation.baseline_parameter_excursion = ...
        task4_cases{1}.parameter_excursion_from_initial;

    assert(validation.disturbance_bound > 0 ...
        && validation.actual_maximum_disturbance ...
        <= validation.disturbance_bound*(1+1e-10), ...
        'Validate_Task4:DisturbanceBoundFailure', ...
        'The configured analytical disturbance bound is invalid.');
    assert(validation.deadzone_threshold ...
        >= validation.deadzone_minimum, ...
        'Validate_Task4:DeadzoneTooSmall', ...
        'The dead-zone threshold does not satisfy the UUB bound.');
    assert(params.task4.sigma > 0 && params.task4.sigma_e > 0, ...
        'Validate_Task4:InvalidLeakage', ...
        'Both leakage coefficients must be positive.');
    assert(validation.ideal_set_margin > 0, ...
        'Validate_Task4:IdealOutsideProjectionSet', ...
        'The projection set must contain the ideal parameters.');
    assert(validation.projection_max_violation < 1e-5, ...
        'Validate_Task4:ProjectionViolation', ...
        'The projection trajectory left its admissible convex set.');
    assert(validation.baseline_parameter_excursion > 1e-6, ...
        'Validate_Task4:NoBaselineDrift', ...
        'The bounded disturbance did not produce observable parameter drift.');
    assert(all(maximum_state_norm < 1), ...
        'Validate_Task4:EmpiricalUnboundedness', ...
        'A Task-4 state trajectory exceeded the conservative UUB check.');
end

function validation = Validate_Task5(params,task5_cases,design)
%VALIDATE_TASK5 Observer, LTR, and adaptive-augmentation checks.

    if numel(task5_cases) ~= 4
        error('Validate_Task5:CaseCount', ...
            'Expected the full-state and three output-feedback cases.');
    end
    configuration_names = cellfun(@(item) item.configuration, ...
        task5_cases,'UniformOutput',false);
    required_configurations = {'fullstate','output_baseline', ...
        'ltr','augmented'};
    assert(isequal(configuration_names,required_configurations), ...
        'Validate_Task5:ConfigurationOrder', ...
        'The Task-5 controller configurations are incomplete.');

    C = params.Cm;
    validation = struct();
    validation.output_dimension = size(C,1);
    validation.state_dimension = size(params.A,1);
    validation.observability_rank = rank(obsv(params.A,C));
    validation.maximum_observer_spectral_abscissa = ...
        max(design.observer_spectral_abscissa);
    validation.maximum_riccati_residual = ...
        max(design.riccati_residual);

    baseline_index = params.task5.baseline_rho_index;
    selected_index = params.task5.selected_rho_index;
    validation.ltr_recovery_improvement = ...
        design.recovery_log_sv_rmse(baseline_index) ...
        /design.recovery_log_sv_rmse(selected_index);
    validation.full_sweep_recovery_improvement = ...
        design.recovery_log_sv_rmse(1) ...
        /design.recovery_log_sv_rmse(end);
    validation.observer_gain_increase = ...
        design.observer_gain_norm(selected_index) ...
        /design.observer_gain_norm(baseline_index);

    output_baseline = task5_cases{2};
    ltr_case = task5_cases{3};
    augmented_case = task5_cases{4};
    validation.observer_tail_improvement = ...
        output_baseline.tail_rms_observer_error ...
        /ltr_case.tail_rms_observer_error;
    validation.augmentation_improvement = ...
        ltr_case.tail_rms_tracking_error ...
        /augmented_case.tail_rms_tracking_error;

    maximum_state_norm = zeros(numel(task5_cases),1);
    for case_index = 1:numel(task5_cases)
        case_result = task5_cases{case_index};
        assert(all(isfinite([case_result.x,case_result.xhat, ...
            case_result.e,case_result.u, ...
            case_result.parameter_error_norm]),'all'), ...
            'Validate_Task5:NonFiniteTrajectory', ...
            'A Task-5 trajectory contains a nonfinite value.');
        maximum_state_norm(case_index) = max( ...
            vecnorm(case_result.x,2,2));
    end
    validation.maximum_state_norm = maximum_state_norm;

    assert(validation.output_dimension ...
        < validation.state_dimension, ...
        'Validate_Task5:NotOutputFeedback', ...
        'Task 5 requires fewer measured outputs than states.');
    assert(validation.observability_rank ...
        == validation.state_dimension, ...
        'Validate_Task5:UnobservablePlant', ...
        'The selected plant/output pair must be observable.');
    assert(all(design.observer_spectral_abscissa < 0), ...
        'Validate_Task5:UnstableObserver', ...
        'Every A-LC matrix in the LTR sweep must be Hurwitz.');
    assert(validation.maximum_riccati_residual < 1e-4, ...
        'Validate_Task5:RiccatiResidual', ...
        'An observer Riccati equation has a large residual.');
    assert(validation.ltr_recovery_improvement > 1 ...
        && validation.full_sweep_recovery_improvement > 1, ...
        'Validate_Task5:NoLoopRecovery', ...
        'Decreasing rho did not improve loop-transfer recovery.');
    assert(validation.observer_gain_increase > 1, ...
        'Validate_Task5:NoObserverGainIncrease', ...
        'LTR recovery should increase observer gain.');
    assert(task5_cases{1}.uses_true_state ...
        && all(cellfun(@(item) ~item.uses_true_state, ...
            task5_cases(2:end))), ...
        'Validate_Task5:StateAccessFailure', ...
        'Only the benchmark may use the true state for control.');
    assert(validation.observer_tail_improvement > 1, ...
        'Validate_Task5:NoObserverImprovement', ...
        'The selected LTR gain did not reduce observer error.');
    assert(validation.augmentation_improvement > 1, ...
        'Validate_Task5:NoAugmentationImprovement', ...
        'Adaptive augmentation did not improve tail tracking.');
    assert(augmented_case.maximum_augmentation_effort > 0, ...
        'Validate_Task5:InactiveAugmentation', ...
        'The adaptive augmentation never became active.');
    assert(all(maximum_state_norm < 2), ...
        'Validate_Task5:EmpiricalUnboundedness', ...
        'A Task-5 trajectory exceeded the conservative bound check.');
end

function evaluation = run_task6_evaluation(base_params)
% Run every controller against the same five scenarios.

    scenario_labels = {'Nominal','Constant disturbance', ...
        'Sinusoidal disturbance','Parameter step','Sensor noise'};
    controller_labels = {'Direct MRAC','Indirect MRAC', ...
        'Integral MRAC','Dead-zone MRAC','Sigma MRAC', ...
        'e-modification','Projection MRAC','LTR + augmentation'};

    previous_rng = rng;
    restore_rng = onCleanup(@() rng(previous_rng));
    rng(41,'twister');
    noise_std = [deg2rad(0.03)*ones(3,1);8e-4*ones(3,1)];
    noise_frequency = linspace(2,18,24);
    noise_cosine = randn(6,numel(noise_frequency));
    noise_sine = randn(6,numel(noise_frequency));

    n_scenarios = numel(scenario_labels);
    n_controllers = numel(controller_labels);
    scenario_results = repmat(struct('label','', ...
        'cases',{{}},'event_time',NaN, ...
        'parameter_step_time',NaN),1,n_scenarios);
    rms_tracking_error = zeros(n_scenarios,n_controllers);
    maximum_control_effort = zeros(n_scenarios,n_controllers);
    final_parameter_error = zeros(n_scenarios,n_controllers);

    for scenario_index = 1:n_scenarios
        scenario_params = configure_task6_scenario(base_params, ...
            scenario_index,noise_frequency,noise_cosine, ...
            noise_sine,noise_std);

        cases = cell(1,n_controllers);
        cases{1} = Direct_MRAC( ...
            scenario_params,'multisine','baseline');
        cases{2} = Indirect_MRAC(scenario_params,'multisine');
        cases{3} = Integral_MRAC( ...
            scenario_params,'multisine','integral');
        cases{4} = Direct_MRAC( ...
            scenario_params,'multisine','deadzone');
        cases{5} = Direct_MRAC( ...
            scenario_params,'multisine','sigma');
        cases{6} = Direct_MRAC( ...
            scenario_params,'multisine','emod');
        cases{7} = Direct_MRAC( ...
            scenario_params,'multisine','projection');
        cases{8} = OutputFeedback_MRAC( ...
            scenario_params,'multisine','augmented');

        for controller_index = 1:n_controllers
            case_result = cases{controller_index};
            metrics = [case_result.rms_tracking_error, ...
                case_result.maximum_control_effort, ...
                case_result.final_Theta_estimation_error];
            assert(all(isfinite(metrics)) ...
                && all(isfinite([case_result.x,case_result.e, ...
                    case_result.u]),'all'), ...
                'Task6:NonFiniteResult', ...
                'Task 6 produced a nonfinite result.');
            assert(case_result.t(end) >= 0.999*base_params.t_final, ...
                'Task6:IncompleteRun', ...
                'A Task 6 simulation ended before the requested time.');

            rms_tracking_error(scenario_index,controller_index) = ...
                metrics(1);
            maximum_control_effort(scenario_index,controller_index) = ...
                metrics(2);
            final_parameter_error(scenario_index,controller_index) = ...
                metrics(3);
        end

        scenario_results(scenario_index).label = ...
            scenario_labels{scenario_index};
        scenario_results(scenario_index).cases = cases;
        scenario_results(scenario_index).event_time = ...
            scenario_params.task6.event_time;
        if scenario_params.task6.parameter_step.enabled
            scenario_results(scenario_index).parameter_step_time = ...
                scenario_params.task6.parameter_step.time;
        end
    end

    scenario_name = repelem(string(scenario_labels(:)),n_controllers);
    controller_name = repmat(string(controller_labels(:)),n_scenarios,1);
    rms_column = reshape(rms_tracking_error.',[],1);
    effort_column = reshape(maximum_control_effort.',[],1);
    parameter_column = reshape(final_parameter_error.',[],1);

    evaluation = struct();
    evaluation.scenario_labels = scenario_labels;
    evaluation.controller_labels = controller_labels;
    evaluation.scenarios = scenario_results;
    evaluation.rms_tracking_error = rms_tracking_error;
    evaluation.maximum_control_effort = maximum_control_effort;
    evaluation.final_parameter_error = final_parameter_error;
    evaluation.summary = table(scenario_name,controller_name, ...
        rms_column,effort_column,parameter_column, ...
        'VariableNames',{'scenario','controller', ...
        'rms_tracking_error','maximum_control_effort', ...
        'final_Theta_estimation_error'});

    clear restore_rng;
end

function params = configure_task6_scenario( ...
        base_params,scenario_index,noise_frequency,noise_cosine, ...
        noise_sine,noise_std)
% Set the plant change, disturbance, and common sensor signal.

    params = base_params;
    params.disturbance.type = 'none';
    params.disturbance.start_time = 0;
    params.disturbance.constant = zeros(6,1);
    params.disturbance.amplitude = zeros(6,1);
    params.disturbance.frequency = zeros(6,1);

    params.task6.parameter_step.enabled = false;
    params.task6.parameter_step.time = 0.5*params.t_final;
    params.task6.parameter_step.Lambda_post = params.Lambda_true;
    params.task6.parameter_step.Theta_plant_T_post = ...
        params.Theta_plant_T;
    params.task6.event_time = NaN;
    params.task6.state_noise = @(t) zeros(6,1)+0*t;
    params.task6.output_noise = @(t) zeros(3,1)+0*t;

    disturbance_bound = 0;
    noise_bound = 0;
    switch scenario_index
        case 1
            params.task6.description = ...
                'No disturbance, nominal plant, exact initial parameters';

        case 2
            input_disturbance = [0.004;-0.003;0.004];
            params.disturbance.type = 'constant';
            params.disturbance.start_time = 0.2*params.t_final;
            params.task6.event_time = params.disturbance.start_time;
            params.disturbance.constant = params.B*input_disturbance;
            disturbance_bound = norm(params.disturbance.constant,2);
            params.task6.description = ...
                'Matched constant disturbance at the plant input';

        case 3
            input_amplitude = [0.004;0.003;0.0035];
            input_frequency = [0.37;0.61;0.83];
            input_phase = [0;0.7;1.3];
            params.disturbance.type = 'multisine';
            params.disturbance.start_time = 0.2*params.t_final;
            params.task6.event_time = params.disturbance.start_time;
            params.disturbance.amplitude = zeros(6,3);
            for input_index = 1:3
                params.disturbance.amplitude(:,input_index) = ...
                    params.B(:,input_index)*input_amplitude(input_index);
            end
            params.disturbance.frequency = repmat( ...
                input_frequency.',6,1);
            params.disturbance.phase = repmat(input_phase.',6,1);
            disturbance_bound = norm(sum( ...
                abs(params.disturbance.amplitude),2),2);
            params.task6.description = ...
                'Matched sinusoids with three unknown frequencies';

        case 4
            params.task6.parameter_step.enabled = true;
            params.task6.event_time = params.task6.parameter_step.time;
            params.task6.parameter_step.Lambda_post = [ ...
                0.82,0.03,0.00;
                0.03,0.90,0.02;
                0.00,0.02,0.78];
            params.task6.parameter_step.Theta_plant_T_post = ...
                1.18*params.Theta_plant_T;
            params.task6.description = ...
                'Step change in effectiveness and rotational uncertainty';

        case 5
            params.task6.state_noise = @(t) task6_gaussian_noise( ...
                t,noise_frequency,noise_cosine,noise_sine,noise_std);
            params.task6.output_noise = @(t) params.Cm ...
                *task6_gaussian_noise(t,noise_frequency, ...
                noise_cosine,noise_sine,noise_std);
            noise_bound = 3*norm(noise_std,2);
            params.task6.description = ...
                'Shared zero-mean band-limited Gaussian sensor noise';
    end

    params.task4.disturbance_bound = disturbance_bound;
    disturbance_threshold = 2*norm(params.P,2)*disturbance_bound ...
        /min(eig(params.Q));
    params.task4.deadzone_minimum = disturbance_threshold;
    params.task4.deadzone_epsilon = max(1e-5, ...
        1.10*disturbance_threshold+noise_bound);

    Lambda_post = params.task6.parameter_step.Lambda_post;
    Theta_post = params.task6.parameter_step.Theta_plant_T_post;
    Kx_post = (Lambda_post\ ...
        (params.G\[-params.Kp,-params.Kd])).';
    Kr_post = (Lambda_post\(params.G\params.Kp)).';
    Theta_star_post = (Lambda_post\Theta_post).';

    params.task4.projection.Kx_limit = ...
        max(abs(params.Kx_star),abs(Kx_post))+0.01;
    params.task4.projection.Kr_limit = ...
        max(abs(params.Kr_star),abs(Kr_post))+0.01;
    params.task4.projection.Theta_limit = ...
        max(abs(params.Theta_star),abs(Theta_star_post))+0.005;
    params.task4.projection.Kx_lower = ...
        -params.task4.projection.Kx_limit;
    params.task4.projection.Kx_upper = ...
        params.task4.projection.Kx_limit;
    params.task4.projection.Kr_lower = ...
        -params.task4.projection.Kr_limit;
    params.task4.projection.Kr_upper = ...
        params.task4.projection.Kr_limit;
    params.task4.projection.Theta_lower = ...
        -params.task4.projection.Theta_limit;
    params.task4.projection.Theta_upper = ...
        params.task4.projection.Theta_limit;
end

function noise = task6_gaussian_noise( ...
        t,frequency,cosine_coefficient,sine_coefficient,noise_std)
% Smooth band-limited Gaussian process shared by every controller.

    phase = frequency*t;
    noise = noise_std.*sum(cosine_coefficient.*cos(phase) ...
        +sine_coefficient.*sin(phase),2)/sqrt(numel(frequency));
end
