function [projected_derivative,active_count] = Projection_Operator( ...
        estimate,proposed_derivative,lower_bound,upper_bound)
%PROJECTION_OPERATOR Keep the estimate inside a componentwise box.
%   Omega = {estimate : lower_bound <= estimate <= upper_bound}.
% Outward updates are removed at the boundary.

    if ~isequal(size(estimate),size(proposed_derivative), ...
            size(lower_bound),size(upper_bound))
        error('Projection_Operator:DimensionMismatch', ...
            'Estimate, derivative, and bound arrays must have equal size.');
    end
    if any(~isfinite([estimate(:);proposed_derivative(:); ...
            lower_bound(:);upper_bound(:)]))
        error('Projection_Operator:NonFiniteInput', ...
            'Projection inputs must be finite.');
    end
    if any(lower_bound >= upper_bound,'all')
        error('Projection_Operator:InvalidBounds', ...
            'Every lower bound must be strictly below its upper bound.');
    end

    projected_derivative = proposed_derivative;
    scale = max(1,max(abs([lower_bound(:);upper_bound(:)])));
    tolerance = 100*eps(scale);

    outward_upper = estimate >= upper_bound-tolerance ...
        & proposed_derivative > 0;
    outward_lower = estimate <= lower_bound+tolerance ...
        & proposed_derivative < 0;

    projected_derivative(outward_upper | outward_lower) = 0;

    % Pull trial ODE stages back when roundoff places them outside the box.
    recovery_rate = 100;
    above_upper = estimate > upper_bound;
    below_lower = estimate < lower_bound;
    projected_derivative(above_upper) = min( ...
        proposed_derivative(above_upper), ...
        -recovery_rate*(estimate(above_upper) ...
            -upper_bound(above_upper)));
    projected_derivative(below_lower) = max( ...
        proposed_derivative(below_lower), ...
        recovery_rate*(lower_bound(below_lower) ...
            -estimate(below_lower)));

    active_count = nnz(outward_upper | outward_lower ...
        | above_upper | below_lower);
end
